/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.{js,ts,tsx}',
    './src/**/*.{js,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: { light: '#FFFFFF', dark: '#000000' },
        surface: { light: '#F5F5F5', dark: '#1C1C1E' },
        'surface-hover': { light: '#EBEBEB', dark: '#2C2C2E' },
        text: { light: '#1A1A1A', dark: '#FFFFFF' },
        'text-secondary': { light: '#666666', dark: '#8E8E93' },
        'text-tertiary': { light: '#999999', dark: '#636366' },
        primary: { light: '#007AFF', dark: '#0A84FF' },
        'primary-hover': { light: '#0066DD', dark: '#409CFF' },
        error: { light: '#FF3B30', dark: '#FF453A' },
        'error-hover': { light: '#DD2F28', dark: '#FF6961' },
        success: { light: '#34C759', dark: '#30D158' },
        warning: { light: '#FF9500', dark: '#FF9F0A' },
        border: { light: '#E5E5E5', dark: '#38383A' },
        'border-hover': { light: '#CCCCCC', dark: '#48484A' },
        skeleton: { light: '#E5E5E5', dark: '#38383A' },
        'skeleton-highlight': { light: '#F5F5F5', dark: '#48484A' },
      },
      spacing: {
        xxs: '2px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        xxl: '32px',
        xxxl: '48px',
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
      },
      fontSize: {
        xs: '12px',
        sm: '14px',
        md: '16px',
        lg: '18px',
        xl: '20px',
        xxl: '24px',
        xxxl: '32px',
      },
    },
  },
  plugins: [],
};
